// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface CreateMemberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateMemberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string membershipType = 2;</code>
   * @return The membershipType.
   */
  java.lang.String getMembershipType();
  /**
   * <code>string membershipType = 2;</code>
   * @return The bytes for membershipType.
   */
  com.google.protobuf.ByteString
      getMembershipTypeBytes();
}
