// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface CreateCourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateCourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 capacity = 2;</code>
   * @return The capacity.
   */
  int getCapacity();

  /**
   * <code>int64 trainerId = 3;</code>
   * @return The trainerId.
   */
  long getTrainerId();
}
