// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetAllTrainersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllTrainersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  java.util.List<de.thws.fiw.gymmanagement.application.GetTrainerResponse> 
      getTrainersList();
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetTrainerResponse getTrainers(int index);
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  int getTrainersCount();
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  java.util.List<? extends de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder> 
      getTrainersOrBuilderList();
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder getTrainersOrBuilder(
      int index);
}
