// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

/**
 * Protobuf type {@code GetAllTrainersResponse}
 */
public final class GetAllTrainersResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetAllTrainersResponse)
    GetAllTrainersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 4,
      /* suffix= */ "",
      GetAllTrainersResponse.class.getName());
  }
  // Use GetAllTrainersResponse.newBuilder() to construct.
  private GetAllTrainersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetAllTrainersResponse() {
    trainers_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllTrainersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllTrainersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.class, de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.Builder.class);
  }

  public static final int TRAINERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<de.thws.fiw.gymmanagement.application.GetTrainerResponse> trainers_;
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<de.thws.fiw.gymmanagement.application.GetTrainerResponse> getTrainersList() {
    return trainers_;
  }
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder> 
      getTrainersOrBuilderList() {
    return trainers_;
  }
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  @java.lang.Override
  public int getTrainersCount() {
    return trainers_.size();
  }
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetTrainerResponse getTrainers(int index) {
    return trainers_.get(index);
  }
  /**
   * <code>repeated .GetTrainerResponse trainers = 1;</code>
   */
  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder getTrainersOrBuilder(
      int index) {
    return trainers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < trainers_.size(); i++) {
      output.writeMessage(1, trainers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < trainers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, trainers_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.thws.fiw.gymmanagement.application.GetAllTrainersResponse)) {
      return super.equals(obj);
    }
    de.thws.fiw.gymmanagement.application.GetAllTrainersResponse other = (de.thws.fiw.gymmanagement.application.GetAllTrainersResponse) obj;

    if (!getTrainersList()
        .equals(other.getTrainersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTrainersCount() > 0) {
      hash = (37 * hash) + TRAINERS_FIELD_NUMBER;
      hash = (53 * hash) + getTrainersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.thws.fiw.gymmanagement.application.GetAllTrainersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllTrainersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllTrainersResponse)
      de.thws.fiw.gymmanagement.application.GetAllTrainersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllTrainersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllTrainersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.class, de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.Builder.class);
    }

    // Construct using de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (trainersBuilder_ == null) {
        trainers_ = java.util.Collections.emptyList();
      } else {
        trainers_ = null;
        trainersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllTrainersResponse_descriptor;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetAllTrainersResponse getDefaultInstanceForType() {
      return de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetAllTrainersResponse build() {
      de.thws.fiw.gymmanagement.application.GetAllTrainersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetAllTrainersResponse buildPartial() {
      de.thws.fiw.gymmanagement.application.GetAllTrainersResponse result = new de.thws.fiw.gymmanagement.application.GetAllTrainersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.thws.fiw.gymmanagement.application.GetAllTrainersResponse result) {
      if (trainersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trainers_ = java.util.Collections.unmodifiableList(trainers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trainers_ = trainers_;
      } else {
        result.trainers_ = trainersBuilder_.build();
      }
    }

    private void buildPartial0(de.thws.fiw.gymmanagement.application.GetAllTrainersResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.thws.fiw.gymmanagement.application.GetAllTrainersResponse) {
        return mergeFrom((de.thws.fiw.gymmanagement.application.GetAllTrainersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.thws.fiw.gymmanagement.application.GetAllTrainersResponse other) {
      if (other == de.thws.fiw.gymmanagement.application.GetAllTrainersResponse.getDefaultInstance()) return this;
      if (trainersBuilder_ == null) {
        if (!other.trainers_.isEmpty()) {
          if (trainers_.isEmpty()) {
            trainers_ = other.trainers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTrainersIsMutable();
            trainers_.addAll(other.trainers_);
          }
          onChanged();
        }
      } else {
        if (!other.trainers_.isEmpty()) {
          if (trainersBuilder_.isEmpty()) {
            trainersBuilder_.dispose();
            trainersBuilder_ = null;
            trainers_ = other.trainers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            trainersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTrainersFieldBuilder() : null;
          } else {
            trainersBuilder_.addAllMessages(other.trainers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              de.thws.fiw.gymmanagement.application.GetTrainerResponse m =
                  input.readMessage(
                      de.thws.fiw.gymmanagement.application.GetTrainerResponse.parser(),
                      extensionRegistry);
              if (trainersBuilder_ == null) {
                ensureTrainersIsMutable();
                trainers_.add(m);
              } else {
                trainersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<de.thws.fiw.gymmanagement.application.GetTrainerResponse> trainers_ =
      java.util.Collections.emptyList();
    private void ensureTrainersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trainers_ = new java.util.ArrayList<de.thws.fiw.gymmanagement.application.GetTrainerResponse>(trainers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        de.thws.fiw.gymmanagement.application.GetTrainerResponse, de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder, de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder> trainersBuilder_;

    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public java.util.List<de.thws.fiw.gymmanagement.application.GetTrainerResponse> getTrainersList() {
      if (trainersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trainers_);
      } else {
        return trainersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public int getTrainersCount() {
      if (trainersBuilder_ == null) {
        return trainers_.size();
      } else {
        return trainersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetTrainerResponse getTrainers(int index) {
      if (trainersBuilder_ == null) {
        return trainers_.get(index);
      } else {
        return trainersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder setTrainers(
        int index, de.thws.fiw.gymmanagement.application.GetTrainerResponse value) {
      if (trainersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrainersIsMutable();
        trainers_.set(index, value);
        onChanged();
      } else {
        trainersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder setTrainers(
        int index, de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder builderForValue) {
      if (trainersBuilder_ == null) {
        ensureTrainersIsMutable();
        trainers_.set(index, builderForValue.build());
        onChanged();
      } else {
        trainersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder addTrainers(de.thws.fiw.gymmanagement.application.GetTrainerResponse value) {
      if (trainersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrainersIsMutable();
        trainers_.add(value);
        onChanged();
      } else {
        trainersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder addTrainers(
        int index, de.thws.fiw.gymmanagement.application.GetTrainerResponse value) {
      if (trainersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrainersIsMutable();
        trainers_.add(index, value);
        onChanged();
      } else {
        trainersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder addTrainers(
        de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder builderForValue) {
      if (trainersBuilder_ == null) {
        ensureTrainersIsMutable();
        trainers_.add(builderForValue.build());
        onChanged();
      } else {
        trainersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder addTrainers(
        int index, de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder builderForValue) {
      if (trainersBuilder_ == null) {
        ensureTrainersIsMutable();
        trainers_.add(index, builderForValue.build());
        onChanged();
      } else {
        trainersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder addAllTrainers(
        java.lang.Iterable<? extends de.thws.fiw.gymmanagement.application.GetTrainerResponse> values) {
      if (trainersBuilder_ == null) {
        ensureTrainersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trainers_);
        onChanged();
      } else {
        trainersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder clearTrainers() {
      if (trainersBuilder_ == null) {
        trainers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        trainersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public Builder removeTrainers(int index) {
      if (trainersBuilder_ == null) {
        ensureTrainersIsMutable();
        trainers_.remove(index);
        onChanged();
      } else {
        trainersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder getTrainersBuilder(
        int index) {
      return getTrainersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder getTrainersOrBuilder(
        int index) {
      if (trainersBuilder_ == null) {
        return trainers_.get(index);  } else {
        return trainersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public java.util.List<? extends de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder> 
         getTrainersOrBuilderList() {
      if (trainersBuilder_ != null) {
        return trainersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trainers_);
      }
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder addTrainersBuilder() {
      return getTrainersFieldBuilder().addBuilder(
          de.thws.fiw.gymmanagement.application.GetTrainerResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder addTrainersBuilder(
        int index) {
      return getTrainersFieldBuilder().addBuilder(
          index, de.thws.fiw.gymmanagement.application.GetTrainerResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .GetTrainerResponse trainers = 1;</code>
     */
    public java.util.List<de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder> 
         getTrainersBuilderList() {
      return getTrainersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        de.thws.fiw.gymmanagement.application.GetTrainerResponse, de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder, de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder> 
        getTrainersFieldBuilder() {
      if (trainersBuilder_ == null) {
        trainersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            de.thws.fiw.gymmanagement.application.GetTrainerResponse, de.thws.fiw.gymmanagement.application.GetTrainerResponse.Builder, de.thws.fiw.gymmanagement.application.GetTrainerResponseOrBuilder>(
                trainers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trainers_ = null;
      }
      return trainersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetAllTrainersResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllTrainersResponse)
  private static final de.thws.fiw.gymmanagement.application.GetAllTrainersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.thws.fiw.gymmanagement.application.GetAllTrainersResponse();
  }

  public static de.thws.fiw.gymmanagement.application.GetAllTrainersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllTrainersResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllTrainersResponse>() {
    @java.lang.Override
    public GetAllTrainersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllTrainersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllTrainersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetAllTrainersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

