// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetAllMembersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllMembersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetMemberResponse members = 1;</code>
   */
  java.util.List<de.thws.fiw.gymmanagement.application.GetMemberResponse> 
      getMembersList();
  /**
   * <code>repeated .GetMemberResponse members = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetMemberResponse getMembers(int index);
  /**
   * <code>repeated .GetMemberResponse members = 1;</code>
   */
  int getMembersCount();
  /**
   * <code>repeated .GetMemberResponse members = 1;</code>
   */
  java.util.List<? extends de.thws.fiw.gymmanagement.application.GetMemberResponseOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <code>repeated .GetMemberResponse members = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetMemberResponseOrBuilder getMembersOrBuilder(
      int index);
}
