// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetAllBookingsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllBookingsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  java.util.List<de.thws.fiw.gymmanagement.application.GetBookingResponse> 
      getBookingsList();
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetBookingResponse getBookings(int index);
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  int getBookingsCount();
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  java.util.List<? extends de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder> 
      getBookingsOrBuilderList();
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder getBookingsOrBuilder(
      int index);
}
