// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

/**
 * Protobuf type {@code GetAllBookingsResponse}
 */
public final class GetAllBookingsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetAllBookingsResponse)
    GetAllBookingsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 4,
      /* suffix= */ "",
      GetAllBookingsResponse.class.getName());
  }
  // Use GetAllBookingsResponse.newBuilder() to construct.
  private GetAllBookingsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetAllBookingsResponse() {
    bookings_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllBookingsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllBookingsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.class, de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.Builder.class);
  }

  public static final int BOOKINGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<de.thws.fiw.gymmanagement.application.GetBookingResponse> bookings_;
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<de.thws.fiw.gymmanagement.application.GetBookingResponse> getBookingsList() {
    return bookings_;
  }
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder> 
      getBookingsOrBuilderList() {
    return bookings_;
  }
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  @java.lang.Override
  public int getBookingsCount() {
    return bookings_.size();
  }
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetBookingResponse getBookings(int index) {
    return bookings_.get(index);
  }
  /**
   * <code>repeated .GetBookingResponse bookings = 1;</code>
   */
  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder getBookingsOrBuilder(
      int index) {
    return bookings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bookings_.size(); i++) {
      output.writeMessage(1, bookings_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bookings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bookings_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.thws.fiw.gymmanagement.application.GetAllBookingsResponse)) {
      return super.equals(obj);
    }
    de.thws.fiw.gymmanagement.application.GetAllBookingsResponse other = (de.thws.fiw.gymmanagement.application.GetAllBookingsResponse) obj;

    if (!getBookingsList()
        .equals(other.getBookingsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBookingsCount() > 0) {
      hash = (37 * hash) + BOOKINGS_FIELD_NUMBER;
      hash = (53 * hash) + getBookingsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.thws.fiw.gymmanagement.application.GetAllBookingsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllBookingsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllBookingsResponse)
      de.thws.fiw.gymmanagement.application.GetAllBookingsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllBookingsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllBookingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.class, de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.Builder.class);
    }

    // Construct using de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
      } else {
        bookings_ = null;
        bookingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetAllBookingsResponse_descriptor;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetAllBookingsResponse getDefaultInstanceForType() {
      return de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetAllBookingsResponse build() {
      de.thws.fiw.gymmanagement.application.GetAllBookingsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetAllBookingsResponse buildPartial() {
      de.thws.fiw.gymmanagement.application.GetAllBookingsResponse result = new de.thws.fiw.gymmanagement.application.GetAllBookingsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.thws.fiw.gymmanagement.application.GetAllBookingsResponse result) {
      if (bookingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bookings_ = java.util.Collections.unmodifiableList(bookings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookings_ = bookings_;
      } else {
        result.bookings_ = bookingsBuilder_.build();
      }
    }

    private void buildPartial0(de.thws.fiw.gymmanagement.application.GetAllBookingsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.thws.fiw.gymmanagement.application.GetAllBookingsResponse) {
        return mergeFrom((de.thws.fiw.gymmanagement.application.GetAllBookingsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.thws.fiw.gymmanagement.application.GetAllBookingsResponse other) {
      if (other == de.thws.fiw.gymmanagement.application.GetAllBookingsResponse.getDefaultInstance()) return this;
      if (bookingsBuilder_ == null) {
        if (!other.bookings_.isEmpty()) {
          if (bookings_.isEmpty()) {
            bookings_ = other.bookings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBookingsIsMutable();
            bookings_.addAll(other.bookings_);
          }
          onChanged();
        }
      } else {
        if (!other.bookings_.isEmpty()) {
          if (bookingsBuilder_.isEmpty()) {
            bookingsBuilder_.dispose();
            bookingsBuilder_ = null;
            bookings_ = other.bookings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bookingsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getBookingsFieldBuilder() : null;
          } else {
            bookingsBuilder_.addAllMessages(other.bookings_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              de.thws.fiw.gymmanagement.application.GetBookingResponse m =
                  input.readMessage(
                      de.thws.fiw.gymmanagement.application.GetBookingResponse.parser(),
                      extensionRegistry);
              if (bookingsBuilder_ == null) {
                ensureBookingsIsMutable();
                bookings_.add(m);
              } else {
                bookingsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<de.thws.fiw.gymmanagement.application.GetBookingResponse> bookings_ =
      java.util.Collections.emptyList();
    private void ensureBookingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bookings_ = new java.util.ArrayList<de.thws.fiw.gymmanagement.application.GetBookingResponse>(bookings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        de.thws.fiw.gymmanagement.application.GetBookingResponse, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder, de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder> bookingsBuilder_;

    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public java.util.List<de.thws.fiw.gymmanagement.application.GetBookingResponse> getBookingsList() {
      if (bookingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookings_);
      } else {
        return bookingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public int getBookingsCount() {
      if (bookingsBuilder_ == null) {
        return bookings_.size();
      } else {
        return bookingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetBookingResponse getBookings(int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);
      } else {
        return bookingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder setBookings(
        int index, de.thws.fiw.gymmanagement.application.GetBookingResponse value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.set(index, value);
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder setBookings(
        int index, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder addBookings(de.thws.fiw.gymmanagement.application.GetBookingResponse value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder addBookings(
        int index, de.thws.fiw.gymmanagement.application.GetBookingResponse value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(index, value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder addBookings(
        de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder addBookings(
        int index, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder addAllBookings(
        java.lang.Iterable<? extends de.thws.fiw.gymmanagement.application.GetBookingResponse> values) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookings_);
        onChanged();
      } else {
        bookingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder clearBookings() {
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public Builder removeBookings(int index) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.remove(index);
        onChanged();
      } else {
        bookingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder getBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder getBookingsOrBuilder(
        int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);  } else {
        return bookingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public java.util.List<? extends de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder> 
         getBookingsOrBuilderList() {
      if (bookingsBuilder_ != null) {
        return bookingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookings_);
      }
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder addBookingsBuilder() {
      return getBookingsFieldBuilder().addBuilder(
          de.thws.fiw.gymmanagement.application.GetBookingResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder addBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().addBuilder(
          index, de.thws.fiw.gymmanagement.application.GetBookingResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .GetBookingResponse bookings = 1;</code>
     */
    public java.util.List<de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder> 
         getBookingsBuilderList() {
      return getBookingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        de.thws.fiw.gymmanagement.application.GetBookingResponse, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder, de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder> 
        getBookingsFieldBuilder() {
      if (bookingsBuilder_ == null) {
        bookingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            de.thws.fiw.gymmanagement.application.GetBookingResponse, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder, de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder>(
                bookings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bookings_ = null;
      }
      return bookingsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetAllBookingsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllBookingsResponse)
  private static final de.thws.fiw.gymmanagement.application.GetAllBookingsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.thws.fiw.gymmanagement.application.GetAllBookingsResponse();
  }

  public static de.thws.fiw.gymmanagement.application.GetAllBookingsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllBookingsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllBookingsResponse>() {
    @java.lang.Override
    public GetAllBookingsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllBookingsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllBookingsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetAllBookingsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

