// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetAllCoursesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllCoursesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  java.util.List<de.thws.fiw.gymmanagement.application.GetCourseResponse> 
      getCoursesList();
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetCourseResponse getCourses(int index);
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  int getCoursesCount();
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  java.util.List<? extends de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder> 
      getCoursesOrBuilderList();
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder getCoursesOrBuilder(
      int index);
}
