// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

/**
 * Protobuf type {@code GetBookingResponse}
 */
public final class GetBookingResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetBookingResponse)
    GetBookingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 4,
      /* suffix= */ "",
      GetBookingResponse.class.getName());
  }
  // Use GetBookingResponse.newBuilder() to construct.
  private GetBookingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetBookingResponse() {
    bookingDate_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetBookingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetBookingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.thws.fiw.gymmanagement.application.GetBookingResponse.class, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder.class);
  }

  public static final int BOOKINGID_FIELD_NUMBER = 1;
  private long bookingId_ = 0L;
  /**
   * <code>int64 bookingId = 1;</code>
   * @return The bookingId.
   */
  @java.lang.Override
  public long getBookingId() {
    return bookingId_;
  }

  public static final int MEMBERID_FIELD_NUMBER = 2;
  private long memberId_ = 0L;
  /**
   * <code>int64 memberId = 2;</code>
   * @return The memberId.
   */
  @java.lang.Override
  public long getMemberId() {
    return memberId_;
  }

  public static final int COURSEID_FIELD_NUMBER = 3;
  private long courseId_ = 0L;
  /**
   * <code>int64 courseId = 3;</code>
   * @return The courseId.
   */
  @java.lang.Override
  public long getCourseId() {
    return courseId_;
  }

  public static final int BOOKINGDATE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bookingDate_ = "";
  /**
   * <code>string bookingDate = 4;</code>
   * @return The bookingDate.
   */
  @java.lang.Override
  public java.lang.String getBookingDate() {
    java.lang.Object ref = bookingDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bookingDate_ = s;
      return s;
    }
  }
  /**
   * <code>string bookingDate = 4;</code>
   * @return The bytes for bookingDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBookingDateBytes() {
    java.lang.Object ref = bookingDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookingDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bookingId_ != 0L) {
      output.writeInt64(1, bookingId_);
    }
    if (memberId_ != 0L) {
      output.writeInt64(2, memberId_);
    }
    if (courseId_ != 0L) {
      output.writeInt64(3, courseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bookingDate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, bookingDate_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bookingId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, bookingId_);
    }
    if (memberId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, memberId_);
    }
    if (courseId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, courseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bookingDate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, bookingDate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.thws.fiw.gymmanagement.application.GetBookingResponse)) {
      return super.equals(obj);
    }
    de.thws.fiw.gymmanagement.application.GetBookingResponse other = (de.thws.fiw.gymmanagement.application.GetBookingResponse) obj;

    if (getBookingId()
        != other.getBookingId()) return false;
    if (getMemberId()
        != other.getMemberId()) return false;
    if (getCourseId()
        != other.getCourseId()) return false;
    if (!getBookingDate()
        .equals(other.getBookingDate())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKINGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBookingId());
    hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemberId());
    hash = (37 * hash) + COURSEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCourseId());
    hash = (37 * hash) + BOOKINGDATE_FIELD_NUMBER;
    hash = (53 * hash) + getBookingDate().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetBookingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.thws.fiw.gymmanagement.application.GetBookingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetBookingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetBookingResponse)
      de.thws.fiw.gymmanagement.application.GetBookingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetBookingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetBookingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.thws.fiw.gymmanagement.application.GetBookingResponse.class, de.thws.fiw.gymmanagement.application.GetBookingResponse.Builder.class);
    }

    // Construct using de.thws.fiw.gymmanagement.application.GetBookingResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bookingId_ = 0L;
      memberId_ = 0L;
      courseId_ = 0L;
      bookingDate_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetBookingResponse_descriptor;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetBookingResponse getDefaultInstanceForType() {
      return de.thws.fiw.gymmanagement.application.GetBookingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetBookingResponse build() {
      de.thws.fiw.gymmanagement.application.GetBookingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetBookingResponse buildPartial() {
      de.thws.fiw.gymmanagement.application.GetBookingResponse result = new de.thws.fiw.gymmanagement.application.GetBookingResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(de.thws.fiw.gymmanagement.application.GetBookingResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bookingId_ = bookingId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.memberId_ = memberId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.courseId_ = courseId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bookingDate_ = bookingDate_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.thws.fiw.gymmanagement.application.GetBookingResponse) {
        return mergeFrom((de.thws.fiw.gymmanagement.application.GetBookingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.thws.fiw.gymmanagement.application.GetBookingResponse other) {
      if (other == de.thws.fiw.gymmanagement.application.GetBookingResponse.getDefaultInstance()) return this;
      if (other.getBookingId() != 0L) {
        setBookingId(other.getBookingId());
      }
      if (other.getMemberId() != 0L) {
        setMemberId(other.getMemberId());
      }
      if (other.getCourseId() != 0L) {
        setCourseId(other.getCourseId());
      }
      if (!other.getBookingDate().isEmpty()) {
        bookingDate_ = other.bookingDate_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bookingId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              memberId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              courseId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              bookingDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long bookingId_ ;
    /**
     * <code>int64 bookingId = 1;</code>
     * @return The bookingId.
     */
    @java.lang.Override
    public long getBookingId() {
      return bookingId_;
    }
    /**
     * <code>int64 bookingId = 1;</code>
     * @param value The bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingId(long value) {

      bookingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bookingId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookingId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bookingId_ = 0L;
      onChanged();
      return this;
    }

    private long memberId_ ;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     * @return This builder for chaining.
     */
    public Builder setMemberId(long value) {

      memberId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      memberId_ = 0L;
      onChanged();
      return this;
    }

    private long courseId_ ;
    /**
     * <code>int64 courseId = 3;</code>
     * @return The courseId.
     */
    @java.lang.Override
    public long getCourseId() {
      return courseId_;
    }
    /**
     * <code>int64 courseId = 3;</code>
     * @param value The courseId to set.
     * @return This builder for chaining.
     */
    public Builder setCourseId(long value) {

      courseId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 courseId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCourseId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      courseId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object bookingDate_ = "";
    /**
     * <code>string bookingDate = 4;</code>
     * @return The bookingDate.
     */
    public java.lang.String getBookingDate() {
      java.lang.Object ref = bookingDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookingDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bookingDate = 4;</code>
     * @return The bytes for bookingDate.
     */
    public com.google.protobuf.ByteString
        getBookingDateBytes() {
      java.lang.Object ref = bookingDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bookingDate = 4;</code>
     * @param value The bookingDate to set.
     * @return This builder for chaining.
     */
    public Builder setBookingDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bookingDate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string bookingDate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookingDate() {
      bookingDate_ = getDefaultInstance().getBookingDate();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string bookingDate = 4;</code>
     * @param value The bytes for bookingDate to set.
     * @return This builder for chaining.
     */
    public Builder setBookingDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bookingDate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:GetBookingResponse)
  }

  // @@protoc_insertion_point(class_scope:GetBookingResponse)
  private static final de.thws.fiw.gymmanagement.application.GetBookingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.thws.fiw.gymmanagement.application.GetBookingResponse();
  }

  public static de.thws.fiw.gymmanagement.application.GetBookingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBookingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetBookingResponse>() {
    @java.lang.Override
    public GetBookingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetBookingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBookingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetBookingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

