// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetBookingByMemberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBookingByMemberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 memberId = 1;</code>
   * @return The memberId.
   */
  long getMemberId();

  /**
   * <code>int32 pagesize = 2;</code>
   * @return The pagesize.
   */
  int getPagesize();

  /**
   * <code>int32 index = 3;</code>
   * @return The index.
   */
  int getIndex();
}
