// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetBookingsByMemberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBookingsByMemberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BookingResponse bookings = 1;</code>
   */
  java.util.List<de.thws.fiw.gymmanagement.application.BookingResponse> 
      getBookingsList();
  /**
   * <code>repeated .BookingResponse bookings = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.BookingResponse getBookings(int index);
  /**
   * <code>repeated .BookingResponse bookings = 1;</code>
   */
  int getBookingsCount();
  /**
   * <code>repeated .BookingResponse bookings = 1;</code>
   */
  java.util.List<? extends de.thws.fiw.gymmanagement.application.BookingResponseOrBuilder> 
      getBookingsOrBuilderList();
  /**
   * <code>repeated .BookingResponse bookings = 1;</code>
   */
  de.thws.fiw.gymmanagement.application.BookingResponseOrBuilder getBookingsOrBuilder(
      int index);
}
