// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetBookingByCourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBookingByCourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 courseId = 1;</code>
   * @return The courseId.
   */
  long getCourseId();

  /**
   * <code>int32 pagesize = 2;</code>
   * @return The pagesize.
   */
  int getPagesize();

  /**
   * <code>int32 index = 3;</code>
   * @return The index.
   */
  int getIndex();
}
