// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetBookingByDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBookingByDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookingDate = 1;</code>
   * @return The bookingDate.
   */
  java.lang.String getBookingDate();
  /**
   * <code>string bookingDate = 1;</code>
   * @return The bytes for bookingDate.
   */
  com.google.protobuf.ByteString
      getBookingDateBytes();

  /**
   * <code>int32 pagesize = 2;</code>
   * @return The pagesize.
   */
  int getPagesize();

  /**
   * <code>int32 index = 3;</code>
   * @return The index.
   */
  int getIndex();
}
