// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

/**
 * Protobuf type {@code GetCoursesByTrainerResponse}
 */
public final class GetCoursesByTrainerResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetCoursesByTrainerResponse)
    GetCoursesByTrainerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 4,
      /* suffix= */ "",
      GetCoursesByTrainerResponse.class.getName());
  }
  // Use GetCoursesByTrainerResponse.newBuilder() to construct.
  private GetCoursesByTrainerResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetCoursesByTrainerResponse() {
    courses_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetCoursesByTrainerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetCoursesByTrainerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.class, de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.Builder.class);
  }

  public static final int COURSES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<de.thws.fiw.gymmanagement.application.GetCourseResponse> courses_;
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  @java.lang.Override
  public java.util.List<de.thws.fiw.gymmanagement.application.GetCourseResponse> getCoursesList() {
    return courses_;
  }
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder> 
      getCoursesOrBuilderList() {
    return courses_;
  }
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  @java.lang.Override
  public int getCoursesCount() {
    return courses_.size();
  }
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetCourseResponse getCourses(int index) {
    return courses_.get(index);
  }
  /**
   * <code>repeated .GetCourseResponse courses = 1;</code>
   */
  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder getCoursesOrBuilder(
      int index) {
    return courses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < courses_.size(); i++) {
      output.writeMessage(1, courses_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < courses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, courses_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse)) {
      return super.equals(obj);
    }
    de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse other = (de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse) obj;

    if (!getCoursesList()
        .equals(other.getCoursesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoursesCount() > 0) {
      hash = (37 * hash) + COURSES_FIELD_NUMBER;
      hash = (53 * hash) + getCoursesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetCoursesByTrainerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetCoursesByTrainerResponse)
      de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetCoursesByTrainerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetCoursesByTrainerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.class, de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.Builder.class);
    }

    // Construct using de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (coursesBuilder_ == null) {
        courses_ = java.util.Collections.emptyList();
      } else {
        courses_ = null;
        coursesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.thws.fiw.gymmanagement.application.Gym.internal_static_GetCoursesByTrainerResponse_descriptor;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse getDefaultInstanceForType() {
      return de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse build() {
      de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse buildPartial() {
      de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse result = new de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse result) {
      if (coursesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.courses_ = courses_;
      } else {
        result.courses_ = coursesBuilder_.build();
      }
    }

    private void buildPartial0(de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse) {
        return mergeFrom((de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse other) {
      if (other == de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse.getDefaultInstance()) return this;
      if (coursesBuilder_ == null) {
        if (!other.courses_.isEmpty()) {
          if (courses_.isEmpty()) {
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoursesIsMutable();
            courses_.addAll(other.courses_);
          }
          onChanged();
        }
      } else {
        if (!other.courses_.isEmpty()) {
          if (coursesBuilder_.isEmpty()) {
            coursesBuilder_.dispose();
            coursesBuilder_ = null;
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coursesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCoursesFieldBuilder() : null;
          } else {
            coursesBuilder_.addAllMessages(other.courses_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              de.thws.fiw.gymmanagement.application.GetCourseResponse m =
                  input.readMessage(
                      de.thws.fiw.gymmanagement.application.GetCourseResponse.parser(),
                      extensionRegistry);
              if (coursesBuilder_ == null) {
                ensureCoursesIsMutable();
                courses_.add(m);
              } else {
                coursesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<de.thws.fiw.gymmanagement.application.GetCourseResponse> courses_ =
      java.util.Collections.emptyList();
    private void ensureCoursesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        courses_ = new java.util.ArrayList<de.thws.fiw.gymmanagement.application.GetCourseResponse>(courses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        de.thws.fiw.gymmanagement.application.GetCourseResponse, de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder, de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder> coursesBuilder_;

    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public java.util.List<de.thws.fiw.gymmanagement.application.GetCourseResponse> getCoursesList() {
      if (coursesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(courses_);
      } else {
        return coursesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public int getCoursesCount() {
      if (coursesBuilder_ == null) {
        return courses_.size();
      } else {
        return coursesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetCourseResponse getCourses(int index) {
      if (coursesBuilder_ == null) {
        return courses_.get(index);
      } else {
        return coursesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder setCourses(
        int index, de.thws.fiw.gymmanagement.application.GetCourseResponse value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.set(index, value);
        onChanged();
      } else {
        coursesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder setCourses(
        int index, de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.set(index, builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder addCourses(de.thws.fiw.gymmanagement.application.GetCourseResponse value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.add(value);
        onChanged();
      } else {
        coursesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder addCourses(
        int index, de.thws.fiw.gymmanagement.application.GetCourseResponse value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.add(index, value);
        onChanged();
      } else {
        coursesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder addCourses(
        de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.add(builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder addCourses(
        int index, de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.add(index, builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder addAllCourses(
        java.lang.Iterable<? extends de.thws.fiw.gymmanagement.application.GetCourseResponse> values) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, courses_);
        onChanged();
      } else {
        coursesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder clearCourses() {
      if (coursesBuilder_ == null) {
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coursesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public Builder removeCourses(int index) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.remove(index);
        onChanged();
      } else {
        coursesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder getCoursesBuilder(
        int index) {
      return getCoursesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder getCoursesOrBuilder(
        int index) {
      if (coursesBuilder_ == null) {
        return courses_.get(index);  } else {
        return coursesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public java.util.List<? extends de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder> 
         getCoursesOrBuilderList() {
      if (coursesBuilder_ != null) {
        return coursesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(courses_);
      }
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder addCoursesBuilder() {
      return getCoursesFieldBuilder().addBuilder(
          de.thws.fiw.gymmanagement.application.GetCourseResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder addCoursesBuilder(
        int index) {
      return getCoursesFieldBuilder().addBuilder(
          index, de.thws.fiw.gymmanagement.application.GetCourseResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .GetCourseResponse courses = 1;</code>
     */
    public java.util.List<de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder> 
         getCoursesBuilderList() {
      return getCoursesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        de.thws.fiw.gymmanagement.application.GetCourseResponse, de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder, de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder> 
        getCoursesFieldBuilder() {
      if (coursesBuilder_ == null) {
        coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            de.thws.fiw.gymmanagement.application.GetCourseResponse, de.thws.fiw.gymmanagement.application.GetCourseResponse.Builder, de.thws.fiw.gymmanagement.application.GetCourseResponseOrBuilder>(
                courses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        courses_ = null;
      }
      return coursesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetCoursesByTrainerResponse)
  }

  // @@protoc_insertion_point(class_scope:GetCoursesByTrainerResponse)
  private static final de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse();
  }

  public static de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCoursesByTrainerResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCoursesByTrainerResponse>() {
    @java.lang.Override
    public GetCoursesByTrainerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCoursesByTrainerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCoursesByTrainerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.thws.fiw.gymmanagement.application.GetCoursesByTrainerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

