// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetCourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 courseId = 1;</code>
   * @return The courseId.
   */
  long getCourseId();
}
