// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetTrainerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTrainerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 trainerId = 1;</code>
   * @return The trainerId.
   */
  long getTrainerId();
}
