// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gym.proto
// Protobuf Java Version: 4.27.4

package de.thws.fiw.gymmanagement.application;

public interface GetTrainerByNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTrainerByNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pagesize = 1;</code>
   * @return The pagesize.
   */
  int getPagesize();

  /**
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
